### ISSUE TITLE
OF0.9.0 & Xcode7.2.1

### ISSUE THREAD

**Issue by vvvgaming** [naus3a/ofxArtool5#3]
hi,naus3a
in example has a problem

 “linker command failed with exit code 1 (use -v to see invocation)”  means 
It‘s compiled at the same time  （The same two projects）？

**Comment by naus3a** [comment]
You probably have wrong references in the xcode project: my setup was evolving while I was working, so maybe a few absolute paths (or weird relative ones) found their way into the project. Just double check that the ARToolKit libraries point to the right place in your system.

**Comment by vvvgaming** [comment]
well,double check ,Thx~
