### ISSUE TITLE
I cannot run an exampleProject with error message

### ISSUE THREAD

**Issue by icq4ever** [naus3a/ofxArtool5#4]
hello. I have a problem with ofxArtool5 addon.

> Error (2): unable to open camera parameters file "\255\276\255\336\336\300ݺ\200F" for reading. No such file or directory.
> [ error ] ofxArtool5::setupCamera(): error loading param file

I fixed search path libraries. so at least I can build but, it crashed with above message.
pattern file and calibration files are exist in bin/data folder.

is there anything I missed?

I build with oF 0.9.3 & xCode 7.2.1.

**Comment by naus3a** [comment]
It sounds like you're missing a file:
- do you have your populated data folder?
- are your file permission set correctly?
- is your project pointing to the right places? (My Xcode project should use relative paths, but I only tested locally, so you should check if paths are still correct in your system)

**Comment by icq4ever** [comment]
hmmm. not one of them.
- not permission issue. I tried with chmod 775 but not different.

check screenshots below
**artool5example**
![screen shot 2016-03-14 at 1 41 44 pm](https://cloud.githubusercontent.com/assets/530796/13735356/bfa218b4-e9eb-11e5-999d-b0772469a659.png)
<img width="1962" alt="screen shot 2016-03-14 at 1 43 08 pm" src="https://cloud.githubusercontent.com/assets/530796/13735360/cbd178be-e9eb-11e5-8b8c-eefffb7dd8e1.png">
<img width="512" alt="screen shot 2016-03-14 at 1 47 59 pm" src="https://cloud.githubusercontent.com/assets/530796/13735364/cf953b52-e9eb-11e5-981b-aabc26990a2c.png">

by the way.. other example(artool5NFTexample folder) have same error message but **not crashed**.
<img width="1484" alt="screen shot 2016-03-14 at 1 49 42 pm" src="https://cloud.githubusercontent.com/assets/530796/13735385/1f0bc30e-e9ec-11e5-98cd-ab863a78e2ee.png">

**Comment by naus3a** [comment]
Your file system looks good and the error you're getting is triggered when the arParamLoad function in ARToolkit cannot load a parameter file.

I'm on XCode 5, so I suspect the problem could originate from the project files.
I'd troubleshoot going through the following steps:
- cout the path you're feeding to the setup function, so you're sure you're pointing to the right place

-manually insert an absolute path to the camera parameter file
- setup a new, clean project and copy/paste the example source
- in case nothing works, I'd test the "vanilla" ARToolkit examples, to be sure everything works.

Normally I don't like to include Xcode files into repos: system and version differences can create trouble, so I think it's always better to make your own project.

**Comment by quietcricket** [comment]
I had same problem but solved by assigning the full path directly to the parameter. I suspect the char pointer is not retained properly. Will let you know once I do more checking.

**Comment by ToolKid** [comment]
In the file ofxARTNftTracker.cpp I changed: 
const char * cPathMarkerParam = ofToDataPath(pthMarkerData).c_str();
into:  
pthMarkerData = ofToDataPath(pthMarkerData,false);
const char * cPathMarkerParam = (const char*) pthMarkerData.c_str();

and 
const char * cPathCamParam = ofToDataPath(pthCamParam).c_str();
into:
pthCamParam = ofToDataPath(pthCamParam,false);
const char * cPathCamParam = (const char*) pthCamParam.c_str();

And it work without adding full path.

**Comment by naus3a** [comment]
explicit cast is probably a good idea, thanks

**Comment by ToolKid** [comment]
It looks like it cast it wrong according to console output: 
Error (2): unable to open camera parameters file "\255\276\255\336\336\300ݺ\220\244" for reading.

**Comment by naus3a** [comment]
Mmh.
The "const" part might be the troublemaker in some cases. Probably a good idea to have a look how they do it in "plain ARToolkit".
