### ISSUE TITLE
"ofxArtoolMode.h" not found

### ISSUE THREAD

**Issue by brinoausrino** [naus3a/ofxArtool5#5]
`ofxArtool5.h` tries to include `ofxArtoolMode.h` and `ofxArtoolModePatt.h` which are not present in the repository. 

Youd have any suggestion?

**Comment by naus3a** [comment]
Yes, sorry: the design of the addon was still a work in progress.
You can safely ignore ofxArtool5.h: 90% it will disappear. Just have a look at the examples and you should be fine.
