### ISSUE TITLE
Issues with cAr2ReadSurfaceSet

### ISSUE THREAD

**Issue by martial** [naus3a/ofxArtool5#7]
Hi,

I'm having some issues reading AR2SurfaceSetT from generated .iset files ( on Mac OS X ) – using ofxArtool5::cAr2ReadSurfaceSet

It seems that It won't load properly the .jpg files, and then crashes.
In the comments I've seen some hacks somewhere, but can't find any way to have it working.
I did some research and I'm getting to a point where I don't know what to do!

Any clue about that ? 

Thanks a lot !

**Comment by naus3a** [comment]
Hey,
sorry for the late reply.

Basically .iset files are not working if OF for some reason I did not manage to figure out. I could not find proper documentation on the file format, but it's pretty clear what needs to be stored in it, so I ended up wrapping my own simple .dat files.

You can easily make your own using the ofxArtool5::saveSurfaceSetData function

**Comment by martial** [comment]
Yes – that's exactly what I tried to say before, I can't find a way to have this function working.
This function need to send an AR2SurfaceSetT * instance, and I understood you can have it using ofxArtool5::cAr2ReadSurfaceSet. 

Unfortunately this function is crashing, or seems uncompleted ?

On other hand I tried to load directly from the markers.dat file.
It seems to work, but the tracking is not working properly. I need to dig on that 

Thanks for your reply!

**Comment by ToolKid** [comment]
According to error: "Falling back to reading '%s%s' in ARToolKit v4.x format.\n"
It looks like function in row 115 ar2ReadJpegImage2 in ar2ReadImageSet fails
https://github.com/artoolkit/artoolkit5/blob/master/lib/SRC/AR2/imageSet.c

**Comment by naus3a** [comment]
It used to work for me, but it's been a while since the last time I used it. Will test.

**Comment by ToolKid** [comment]
There is some strange tracking behaviour with my custom NFT markers. The tracking is periodically interrupted between events marker lost / marker found. I tried the same NFT dataset in native artoolkit app (nftSimple) and the tracking was consistent. I am wondering if this is connected to the loading issue or something else.

**Comment by naus3a** [comment]
Difficult to say: apart from the file format, the NFT data goes into ARToolKit the "vanilla way", so I would expect it to behave properly.
I've been using this addon in the real world for some time, making my own markers and tracking them in a solid way, so my feeling is that it's behaving properly.

That having being said: the addon does not only wrap ARTK functionality, it also add some tracking logic that, while worked the I inteded for myself, might be a trouble maker in your project.
Are you doing something significantly different to what I do in the examples?

**Comment by martial** [comment]
No, just trying to make NFT example work with custom markers ( pinball is super solid tough ).
That said – would be supper happy to help, and contribute to this project !

**Comment by ToolKid** [comment]
I tried yours "plain" example. Pinball is working correctly, but my markers are not. The same markers are working ok within artoolkit example...

**Comment by naus3a** [comment]
If pinball works nice, there might be something weird going on with the creation of new markers: I'll try to put together a walkthrough of I do myself. There might be something I do that it's not 100% evident: I spent some time wrapping my head around it.

@martial  of course: feel free to fork and contribute: I left this addon untouched for quite some time and I imagine some polishing/new features would be helpful to people looking for an OSS way to do AR in OF.

**Comment by martial** [comment]
@naus3a cool!
As soon as I get a more precise view of it and got it working – would be supper happy to help and write example + strongest tutorial

**Comment by ToolKid** [comment]
Hi there, any news?

**Comment by martial** [comment]
On spare time I've been trying a bunch of stuff.
I've been confirming the .iset loading issue ( that's why we have a random detection, only part of the files are loaded ).

So I see two options : 
– Keeping the .dat file system from @naus3a – but for now It seems impossible to create custom data file
 – Trying to find a way to load *.iset files within OF ( that would be the better option ), but It's hard as there is no much information

**Comment by naus3a** [comment]
Sorry people: I'm moving to a new country + contributing to the opening of new studio. I have 0 time at the moment; I'm going to post other examples as soon as I slow down a bit.

**Comment by ToolKid** [comment]
@naus3a it would be great, if you could share with us more examples or just how to implement your custom function. Maybe you have something to share as is, just to look at... all best with your plans.

**Comment by ToolKid** [comment]
It seems that http://artoolkit.org is down...

**Comment by martial** [comment]
Hey just a quick message to say that I've been working on a solid way to create markers etc..
Currenlty working on some cleaning and planning to release something soon! 
Would be super happy to have any input on this

**Comment by naus3a** [comment]
oh cool, keep me updated :)

**Comment by ToolKid** [comment]
any news? thanks!

**Comment by martial** [comment]
Hey, I've been doing a fork of the addon https://github.com/martial/ofxArtool5
You can generate markers ( under Mac OS ) using genTexData binary in Utils folder.
This binary exports the .dat format @naus3a made.

Then It's just a matter of configuration and It should work out of the box using the project generator

**Comment by martial** [comment]
Also updated to 5.4 version, so you can recompile the ArToolKit library directly with your custom settings. 
Going to port to linux very soon
